name: tm8l
description: Project created by Margins brick.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  anchor_scroll_controller: ^0.4.4
  auto_size_text: ^3.0.0
  beamer: ^1.6.0
  chopper: ^7.1.1+1
  chopper_generator: ^7.1.1
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.2.1
  flutter_lints: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  intl: ^0.18.0
  loggy: ^2.0.3
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  skeletonizer: ^1.1.0
  swagger_dart_code_generator: ^2.15.0
  timer_count_down: ^2.2.2

dev_dependencies:
  analyzer: ^5.11.1
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_gen: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Black.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/RedHatDisplay-ExtraBold.ttf
        - asset: assets/fonts/RedHatDisplay-Light.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/luncher_icon.png"
