name: "tm8_game_admin"
description: Project created by Margins brick.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  beamer: ^1.6.0
  blurrycontainer: ^1.0.2
  chopper: ^7.1.1
  chopper_generator: ^7.1.1
  envied: ^0.5.3
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_calendar_carousel: ^2.4.2
  flutter_form_builder: ^9.1.1
  flutter_lints: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_portal: ^1.1.4
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  injectable: ^2.3.2
  intl: ^0.18.0
  isoweek: ^1.1.4
  jwt_decoder: ^2.0.1
  loader_overlay: ^4.0.0
  loggy: ^2.0.3
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1
  swagger_dart_code_generator: ^2.14.2

dev_dependencies:
  analyzer: ^5.11.1
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  flutter_gen: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/common/
    - assets/games/
    - assets/menu/
    - assets/user/
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Black.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/RedHatDisplay-ExtraBold.ttf
        - asset: assets/fonts/RedHatDisplay-Light.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf

flutter_launcher_icons:
  ios: false
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/luncher_icon.png"
