// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqAhvhcRDFYMmkP5j0N6Xf8joxoZQoQ5s',
    appId: '1:212896338218:web:a9471eb37ec5942caa4e53',
    messagingSenderId: '212896338218',
    projectId: 'tm8-gaming',
    authDomain: 'tm8-gaming.firebaseapp.com',
    storageBucket: 'tm8-gaming.appspot.com',
    measurementId: 'G-9G4Q0TKMWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnT-2ptaYe1kx0urfYglFNqwRGZm_f2ug',
    appId: '1:212896338218:android:c243750b663ca600aa4e53',
    messagingSenderId: '212896338218',
    projectId: 'tm8-gaming',
    storageBucket: 'tm8-gaming.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg5DAJts1AOj9OiHlBBP5uLb8SFfNxhi0',
    appId: '1:212896338218:ios:1157ecbc312ad6a8aa4e53',
    messagingSenderId: '212896338218',
    projectId: 'tm8-gaming',
    storageBucket: 'tm8-gaming.appspot.com',
    androidClientId:
        '212896338218-oalu00drf6mi660kbu1e78cv2vm1ocm1.apps.googleusercontent.com',
    iosClientId:
        '212896338218-oalu00drf6mi660kbu1e78cv2vm1ocm1.apps.googleusercontent.com',
    iosBundleId: 'com.tm8.game',
  );
}
