export enum ApexLegendsRank {
  RookieIV = 'rookie-iv',
  RookieIII = 'rookie-iii',
  RookieII = 'rookie-ii',
  RookieI = 'rookie-i',
  BronzeIV = 'bronze-iv',
  BronzeIII = 'bronze-iii',
  BronzeII = 'bronze-ii',
  BronzeI = 'bronze-i',
  SilverIV = 'silver-iv',
  SilverIII = 'silver-iii',
  SilverII = 'silver-ii',
  SilverI = 'silver-i',
  GoldIV = 'gold-iv',
  GoldIII = 'gold-iii',
  GoldII = 'gold-ii',
  GoldI = 'gold-i',
  PlatinumIV = 'platinum-iv',
  PlatinumIII = 'platinum-iii',
  PlatinumII = 'platinum-ii',
  PlatinumI = 'platinum-i',
  DiamondIV = 'diamond-iv',
  DiamondIII = 'diamond-iii',
  DiamondII = 'diamond-ii',
  DiamondI = 'diamond-i',
  Master = 'master',
  ApexPredator = 'apex-predator',
}
