export enum CallOfDutyRank {
  BronzeI = 'bronze-i',
  BronzeII = 'bronze-ii',
  BronzeIII = 'bronze-iii',
  SilverI = 'silver-i',
  SilverII = 'silver-ii',
  SilverIII = 'silver-iii',
  GoldI = 'gold-i',
  GoldII = 'gold-ii',
  GoldIII = 'gold-iii',
  PlatinumI = 'platinum-i',
  PlatinumII = 'platinum-ii',
  PlatinumIII = 'platinum-iii',
  DiamondI = 'diamond-i',
  DiamondII = 'diamond-ii',
  DiamondIII = 'diamond-iii',
  CrimsonI = 'crimson-i',
  CrimsonII = 'crimson-ii',
  CrimsonIII = 'crimson-iii',
  Iridescent = 'iridescent',
  Top250 = 'top-250',
}
