export enum FortniteRank {
  BronzeI = 'bronze-i',
  BronzeII = 'bronze-ii',
  BronzeIII = 'bronze-iii',
  SilverI = 'silver-i',
  SilverII = 'silver-ii',
  SilverIII = 'silver-iii',
  GoldI = 'gold-i',
  GoldII = 'gold-ii',
  GoldIII = 'gold-iii',
  PlatinumI = 'platinum-i',
  PlatinumII = 'platinum-ii',
  PlatinumIII = 'platinum-iii',
  DiamondI = 'diamond-i',
  DiamondII = 'diamond-ii',
  DiamondIII = 'diamond-iii',
  Elite = 'elite',
  Champion = 'champion',
  Unreal = 'unreal',
}
