export enum RocketLeagueRank {
  BronzeI = 'bronze-i',
  BronzeII = 'bronze-ii',
  BronzeIII = 'bronze-iii',
  SilverI = 'silver-i',
  SilverII = 'silver-ii',
  SilverIII = 'silver-iii',
  GoldI = 'gold-i',
  GoldII = 'gold-ii',
  GoldIII = 'gold-iii',
  PlatinumI = 'platinum-i',
  PlatinumII = 'platinum-ii',
  PlatinumIII = 'platinum-iii',
  DiamondI = 'diamond-i',
  DiamondII = 'diamond-ii',
  DiamondIII = 'diamond-iii',
  ChampionI = 'champion-i',
  ChampionII = 'champion-ii',
  ChampionIII = 'champion-iii',
  GrandChampionI = 'grand-champion-i',
  GrandChampionII = 'grand-champion-ii',
  GrandChampionIII = 'grand-champion-iii',
  SupersonicLegend = 'supersonic-legend',
}
