name: "tm8"
description: Project created by Margins brick.
version: 0.6.1+4
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  audio_waveforms: ^1.0.5
  audioplayers: ^6.0.0
  auto_route: ^8.2.0
  blurrycontainer: ^1.0.2
  chopper: ^7.1.1+1
  chopper_generator: ^7.1.1
  country_picker: ^2.0.25
  envied: ^0.5.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.1.1
  flutter_lints: ^3.0.1
  flutter_local_notifications: ^17.1.0
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_native_splash: ^2.4.0
  flutter_portal: ^1.1.4
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.9
  form_builder_validators: ^10.0.1
  freezed_annotation: ^2.4.1
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.0.7
  injectable: ^2.3.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  # language_picker: ^0.4.3
  loader_overlay: ^4.0.0
  loggy: ^2.0.3
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  phone_form_field: ^9.2.3
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  qr_code_dart_scan: ^0.7.6
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0
  skeletonizer: ^1.1.0
  socket_io_client: ^2.0.3+1
  stream_chat: ^7.2.1
  stream_chat_flutter: ^7.2.1
  stream_chat_flutter_core: ^7.2.1
  stream_video_flutter: ^0.3.9
  swagger_dart_code_generator: ^2.15.2
  tcard: ^1.3.5
  url_launcher: ^6.2.5
  webview_flutter: ^4.5.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_gen: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

dependency_overrides:
  # Waiting for https://github.com/GetStream/stream-chat-flutter/issues/1920
  audio_video_progress_bar: ^2.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/common/
    - assets/games/
    - assets/menu/
    - assets/user/
    - assets/settings/
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Black.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/RedHatDisplay-ExtraBold.ttf
        - asset: assets/fonts/RedHatDisplay-Light.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon_ios.png"
  image_path_android: "assets/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/launcher_icon.png"

flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
